### ISSUE TITLE
推荐用黑名单模式,请问黑名单模式是每日同步gfwlist的类容吗?

### ISSUE THREAD

**Issue by aTenb** [GMOogway/shadowrocket-rules#11]
推荐用黑名单模式,请问黑名单模式是每日同步gfwlist的类容吗?

**Comment by aTenb** [comment]
黑名单为什么把苹果apple.com和iCloud.com加入了代理呢?

**Comment by GMOogway** [comment]
> 黑名单为什么把苹果apple.com和iCloud.com加入了代理呢?

规则没错的，www.apple.com在direct列表中，icloud.com cdn域名也是直链的。

**Comment by aTenb** [comment]
![image](https://user-images.githubusercontent.com/35789121/233767771-154bcaed-7a51-4633-b8a7-1ae3c5302bf7.png)

没问题吗

**Comment by GMOogway** [comment]
看了一下上流的数据，的确是在proxy列表中，国内使用 apple.com.cn就行，如果需要 apple.com 走直链，建议采用 custom rule方法。icloud.com同理。
