### ISSUE TITLE
如何解决Bing跳转的问题

### ISSUE THREAD

**Issue by hunter-xue** [GMOogway/shadowrocket-rules#13]
无论是规则还是代理模式，都无法阻止Bing跳转。
使用stash的全局模式一切正常。

**Comment by GMOogway** [comment]
bing.com是在代理列表中的，经实际访问也正常的，不跳转。

**Comment by rockcat-mew** [comment]
iOS，safari浏览器和Bing App依然跳转

**Comment by GMOogway** [comment]
你有时间关注两个问题，一是微软账户所属的国家地区，二是dns是否有污染。

**Comment by rockcat-mew** [comment]
相同的微软账号，MacBook工作正常，没有跳转。国家和地区设置为美国；
DNS污染问题麻烦指点一下，手机和笔记本都在同一个局域网中，笔记本工作正常，没有跳转；

**Comment by rockcat-mew** [comment]
是代理节点的问题，gost+ws+CDN好像有问题，换其他节点一切正常，不再跳转cn.bing

**Comment by cheneyxx** [comment]
用白名单模式  Safari 访问 bing.com 会跳转到 cn.bing.com copilot app 也没法用
