### ISSUE TITLE
网上国网APP提示网络设置了代理

### ISSUE THREAD

**Issue by RainyNightGitHub** [GMOogway/shadowrocket-rules#21]
RT，可否在规则中规避此报错，感谢。

**Comment by GMOogway** [comment]
哪个域名走了代理？试了一下没有弹出提示。

**Comment by RainyNightGitHub** [comment]
https://community.nssurge.com/u/uclort 网上也有类似讨论的，我抓包没看出来。。。但是APP确实一直提示我：“网络设置了代理，请关闭代理重新请求”，然后APP用不了。我的手机是IOS17.1，各个APP都是商店最新版。

**Comment by RainyNightGitHub** [comment]
urge 及 Shadowrocket 在使用「 T3 出行」时遇到「检测到您正在使用网络代理，请关闭网络…」的，可以在文本编辑模式编辑，在 [General] 下的 skip-proxy 增加：[passenger.t3go.cn](http://passenger.t3go.cn/)
注意，[passenger.t3go.cn](http://passenger.t3go.cn/) 和原先内容之间要有英文逗号。
这是另一条评论，原帖地址： https://v2ex.com/t/802669

**Comment by GMOogway** [comment]
@RainyNightGitHub 小火箭->设置->代理->代理类型设成 None 。

**Comment by RainyNightGitHub** [comment]
但作者说会造成部分规则不可用

**Comment by ReedinGod** [comment]
> RT，可否在规则中规避此报错，感谢。

我自己在配置文件中的通用，跳过代理，增加了网址：*.sgcc.com.cn
默认这些都是不写http，然后你想跳过哪个app就找一下那个app的官网
这样虽然还是会有提示，不过已经能正常打开app了
