### ISSUE TITLE
iphone/iPad/mac 谷歌重定向goole.uk问题

### ISSUE THREAD

**Issue by Z01666** [GMOogway/shadowrocket-rules#24]
如下操作后 可以防止将默认搜索引擎设置为Google后，搜索时重定向到Google.uk
![IMG_0018](https://github.com/GMOogway/shadowrocket-rules/assets/100669462/3d1c23b0-bbe9-4bd1-b9ca-ae241abebdd0)
![IMG_0019](https://github.com/GMOogway/shadowrocket-rules/assets/100669462/6bc896de-64ca-4631-b94e-b62c6561db51)
![IMG_0020](https://github.com/GMOogway/shadowrocket-rules/assets/100669462/de1e1c82-15a9-4cea-acbf-d3fdee0450c0)

**Comment by GMOogway** [comment]
这个可以自己写 rewrite 规则。
