### ISSUE TITLE
白名单模式 bing.com 跳转 cn.bing.com copilot app 无法使用

### ISSUE THREAD

**Issue by cheneyxx** [GMOogway/shadowrocket-rules#27]
![1](https://github.com/GMOogway/shadowrocket-rules/assets/10344793/83fbec29-4b6b-4028-bd97-f5b9818907f6)
![2](https://github.com/GMOogway/shadowrocket-rules/assets/10344793/77165cff-7456-4b99-91d9-2c9d2605d80e)
![3](https://github.com/GMOogway/shadowrocket-rules/assets/10344793/14d63419-9b6e-47b8-99da-8e4c05879dbf)
![4](https://github.com/GMOogway/shadowrocket-rules/assets/10344793/a3f2c74a-06cf-4c6b-83c7-4bfc055f86b8)

**Comment by cheneyxx** [comment]
看来只有切黑名单模式哦

**Comment by GMOogway** [comment]
@cheneyxx 你好。规则是没问题的，这个问题涉及到不少因素，不是白名单黑名单的问题，请检查一下你的代理IP地址、地区、语言等设置。

**Comment by GMOogway** [comment]
比如最后一张图的显示，已经检测到你的手机的地区设置是在国内，所以说这个功能你不能用。

**Comment by cheneyxx** [comment]
但是我用 default.conf 和这个规则 https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_cnip.conf 就是正常的

**Comment by cheneyxx** [comment]
https://github.com/GMOogway/shadowrocket-rules/assets/10344793/1f8e1f36-6da9-46dc-b5c6-22ee1c5355a6

**Comment by cheneyxx** [comment]
![WechatIMG109](https://github.com/GMOogway/shadowrocket-rules/assets/10344793/341d2634-025e-427b-9020-a8e6511bffca)

这样就可以了

**Comment by GMOogway** [comment]
你final是proxy，前面二条加了也没用呀，是不是你的geoip数据有问题？

**Comment by cheneyxx** [comment]
我用这个更新了 https://cdn.jsdelivr.net/gh/Hackl0us/GeoIP2-CN@release/Country.mmdb

**Comment by GMOogway** [comment]
这个具体还得你多测试一下，问题是出在哪儿。不管有没有 DOMAIN-SUFFIX,copilot.microsoft.com,Proxy 这一条，我白名单或者是黑名单，配上相应的list，copilot都能正常使用。

**Comment by cheneyxx** [comment]
嗯 反正我得加 bing.com 和 copilot.microsoft.com 代理才能用
