### ISSUE TITLE
建议从直连规则中移除微软境外站点

### ISSUE THREAD

**Issue by jfox7852** [GMOogway/shadowrocket-rules#29]
当前规则微软域名后缀如live.com被设定为直连，但是一些域名实际上是应该代理的，如onedrive.live.com。如果只移除部分被墙域名，又可能会造成使用不同ip登录微软不同服务，容易引起风控。所以不如把微软的境外站点域名都移出直连路由。
曾经尝试前置一个微软网站的模块规则走代理，但是我找到的规则基本都把微软境内部分，比如世纪互联部分也塞进微软列表里去了，所以也不太可行。

**Comment by chenzhiguo** [comment]
附议。
https://copilot.microsoft.com/
https://www.bing.com/
这些网站如果走直连的话，用不了AI服务。

**Comment by GMOogway** [comment]
[https://github.com/GMOogway/shadowrocket-rules/blob/master/factory/proxy_list_append.txt]
