### ISSUE TITLE
快捷指令似乎失效了

### ISSUE THREAD

**Issue by WXqwer** [GMOogway/shadowrocket-rules#4]
快捷指令似乎只能手动点击，无法自动完成。
![03B781AE-4C54-43DA-8C7A-9E2BB014497C](https://user-images.githubusercontent.com/73450696/221323388-c74e79cc-c3ec-402e-8897-40bad6372586.png)

**Comment by GMOogway** [comment]
这个 url scheme 拉起功能是由小火箭提供的，首先确保小火箭装好了，然后手动运行快捷指令能成功不？

**Comment by WXqwer** [comment]
> 

是的，手动是没问题的。

**Comment by GMOogway** [comment]
你编辑那个快捷方式，看它的隐私设置，看看锁定时允许运行的开关有没有打开。

**Comment by WXqwer** [comment]
> 你编辑那个快捷方式，看它的隐私设置，看看锁定时允许运行的开关有没有打开。

我看了下，是打开的。之后我又还原重开了下，再次测试，还是不行......（你是可以的不？
![4F7F3FF5-37DA-49F5-85F8-73D9BA4CF39D](https://user-images.githubusercontent.com/73450696/221326134-a2e3d4d9-4b2b-4dee-a295-f2df8635fab1.png)

**Comment by GMOogway** [comment]
情况是这样子：ios系统出于安全考虑吧，对于某些自动化操作是不允许在锁屏（没解锁）状态下自动执行。所以手动执行能成功（这时是解锁的），但自动化操作时时间一到，如果你刚好在操作手机（解锁了）也是会成功的，如果是锁屏就会失败。折中吧，打开自动化操作的运行前询问选项，时间一到，会有通知等你去操作，你去操作就解锁了，就会成功。

WXqwer ***@***.***>于2023年2月25日 周六08:45写道：

**Comment by WXqwer** [comment]
> 情况是这样子：ios系统出于安全考虑吧，对于某些自动化操作是不允许在锁屏（没解锁）状态下自动执行。所以手动执行能成功（这时是解锁的），但自动化操作时时间一到，如果你刚好在操作手机（解锁了）也是会成功的，如果是锁屏就会失败。折中吧，打开自动化操作的运行前询问选项，时间一到，会有通知等你去操作，你去操作就解锁了，就会成功。 WXqwer ***@***.***>于2023年2月25日 周六08:45写道：
> […](#)
我懂了，一开始我以为可以不解锁自动操作的。（心里还纳闷iOS这么开放了？！笑哭
非常感谢🙏

**Comment by 956836421** [comment]
设置一个敲三下就运行不省事吗
