### ISSUE TITLE
希望增加claude规则

### ISSUE THREAD

**Issue by wojing** [GMOogway/shadowrocket-rules#40]
希望增加claude规则
谢谢

**Comment by GMOogway** [comment]
已增加：
#claude
DOMAIN,cdn.usefathom.com
DOMAIN-SUFFIX,claude.ai
DOMAIN-SUFFIX,anthropic.com
DOMAIN-SUFFIX,intercomcdn.com
DOMAIN-KEYWORD,claude
DOMAIN-KEYWORD,anthropic

**Comment by wojing** [comment]
谢谢
