### ISSUE TITLE
Microsoft store 桌面版WhatsApp二维码无法加载

### ISSUE THREAD

**Issue by shin-kosaki** [GMOogway/shadowrocket-rules#42]
问题重现：
1、手机上使用shadowrocket开启代理共享
2、PC开启代理共享IOS的shadowrocket代理
3、打开WhatsApp PC端无法加载验证码

其他应用无此问题，WhatsApp web和IOS端正常访问

**Comment by PeiChuXueQuKanXue** [comment]
哈喽，请问 后边找到解决方案了么
