### ISSUE TITLE
[Question] How I can add module rules to route traffic for the Agricultural Bank of China without using a proxy？

### ISSUE THREAD

**Issue by Tianci-King** [GMOogway/shadowrocket-rules#45]
The configuration file URL has been imported and configured successfully. However, the rules in your repository do not handle the case for the Agricultural Bank of China. I tried reopening the bank, but I was still prompted that a proxy was being used. Could you please advise how I can add module rules to route traffic for the Agricultural Bank of China without using a proxy?
---------
您好，我已经导入配置文件url 把配置导好了  但是您的仓库的规则并没有处理中国农业银行的情况，我尝试重新打开银行仍然被提示使用了代理，求问我需要如何增加模块规则以分流中国农业银行，使其不走代理？

**Comment by GMOogway** [comment]
你可以新建一个模块，里面写上对农业银行的 direct 规则，并把它移动到最上面，这样它会被最优先匹配处理。
