### ISSUE TITLE
如何解决国内银行app无法登录等相关问题

### ISSUE THREAD

**Issue by jen588** [GMOogway/shadowrocket-rules#46]
作者您好：
       请问在登录国内银行app时，会有使用了代理的提示弹窗导致无法登录，请问这种问题如何解决？
       还有就是能否在proxy规则中加入ipinfo.io这类ip检测网站，用于使用浏览器检测当前代理ip地址的准确性。

**Comment by GMOogway** [comment]
可以自建小模块实现自定义规则。关于检测代理地址，还是你自己把代理模式改成全局比较好。
