### ISSUE TITLE
提问：shadowrocket是否可以替代proxifier？如果可以应该如何配置呢？

### ISSUE THREAD

**Issue by lxy1992** [GMOogway/shadowrocket-rules#5]

**Comment by GMOogway** [comment]
关于 shadowrocket 和 proxifier，探讨。
1、两者的目的相同，都是为了分流；
2、但两者分流的主要方法不一样，shadowrocket使用域名、IP、useragent等分流，更通用，proxifier对程序进行分流；
3、所以通过抓包等形式，用proxifier可以分流的也可以用shadowrocket来分流；
4、最后，面向的平台不一样，shadowrocket用于IOS，接管了所有的流量，而proxifier在IOS上可不能用，因为没有程序列表权限给它。
