### ISSUE TITLE
如何设置某网站不走代理？

### ISSUE THREAD

**Issue by CheerfunYou** [GMOogway/shadowrocket-rules#56]
新手小白想请教一下，如何设置某网站不走代理，添加域名规则为direct，并没有生效，同样的域名在win下的clash，用bypass可以绕过，但在shadowrocket里不知道该怎么设置

**Comment by ajtn123** [comment]
Shadowrocket 模块优先级高于规则，可以新建一个模块，置于proxy和reject模块上方，在模块里写规则。
