### ISSUE TITLE
关于配置文件的问题，以及如何自动选择最快节点的请教

### ISSUE THREAD

**Issue by zhuyuchen-git** [GMOogway/shadowrocket-rules#57]
1.我按照您的顺序将配置文件设置好，并进行了模块化的配置，安全问题是否保证。
2.模块化配置您有写一个需要代理才能访问，一个可以直接访问。是raw为直接访问嘛还是，普通用户应该导入哪个好呢？
3.普通用户是按照DIRECT-PROXY-PROXY的顺序导入就可以成功屏蔽广告这些嘛。这样在app里是direct在最下边，正常使用应该是从上到下reject- direct-proxy这种可以吗？先屏蔽广告，然后在看是不是国内的，最后不是使用代理，这种安全吗

您是否知道如何设置让shadowrocket自动选择最快节点。

**Comment by GMOogway** [comment]
利用小火箭节点组和回退功能。
