### ISSUE TITLE
未找到‘小火箭 -> 配置 -> 模块’添加规则方式

### ISSUE THREAD

**Issue by shengs-UCAS** [GMOogway/shadowrocket-rules#6]
![8341a22d18ffbb416075d59f318f769](https://user-images.githubusercontent.com/84768113/225323645-edb5a2d7-00bc-4477-b87c-54ba911f1e90.jpg)
根据使用方法步骤2，没能在‘配置’页面下找到‘模块’相关设置
请问直接在‘配置’页面点击右上角然后添加三个规则链接可以吗？

**Comment by GMOogway** [comment]
这个…，界面总有些不一样，你可以进脚本订阅里添加。

shengsheng ***@***.***>于2023年3月15日 周三21:36写道：
