### ISSUE TITLE
小火箭规则

### ISSUE THREAD

**Issue by Rowan-pow** [GMOogway/shadowrocket-rules#65]

**Comment by Yyy23333333** [comment]
![IMG_7840](https://github.com/user-attachments/assets/04a275e5-546f-4e09-9cc6-4c95057a650c)

![IMG_7839](https://github.com/user-attachments/assets/2cae9a8b-9c4f-4f7c-86e1-6586273abeed)
大佬，怎么设置苹果音乐不走代理走直连呀？，已经自建了模块排在它们前面，但测试规则还是走的代理
![Uploading IMG_7837.
![IMG_7838](https://github.com/user-attachments/assets/ae6ef273-69a0-47c4-a4e5-783b765de387)
png…]()

**Comment by ajtn123** [comment]
Duplicate of #66
