### ISSUE TITLE
自建规则模块排序在前面但没有效果

### ISSUE THREAD

**Issue by Yyy23333333** [GMOogway/shadowrocket-rules#66]
大佬，怎么设置苹果音乐不走代理走直连呀？已经自建了模块排在它们前面，但测试规则还是走的代理

**Comment by Yyy23333333** [comment]
![IMG_7837](https://github.com/user-attachments/assets/3dc9c1d9-247b-4ac8-adcc-8338cc7436c3)
![IMG_7838](https://github.com/user-attachments/assets/f61bea22-584a-4b88-b1ae-f39045f4f444)
![IMG_7839](https://github.com/user-attachments/assets/588afeb1-57c9-4c5d-9bc7-4e9aadd45495)

**Comment by ajtn123** [comment]
试试模块改成
```
#!name=Name
#!desc=Desc
[Rule]
DOMAIN-SUFFIX,applemusic.com,DIRECT
```

**Comment by Yyy23333333** [comment]
已解决，感谢🙏🏻
