### ISSUE TITLE
微信走代理了

### ISSUE THREAD

**Issue by ZZMISKING** [GMOogway/shadowrocket-rules#7]
用白名单，Final,proxy，微信走代理，可以用小程序查ip看到。 
黑名单，final,direct，走的直连。

**Comment by GMOogway** [comment]
说明它既不在proxy列表中，也不在direct列表中，到时我修改一下使用说明。

ZZMISKING ***@***.***>于2023年3月20日 周一16:33写道：

**Comment by GMOogway** [comment]
白名单时，在`FINAL,PROXY`前面，再加一句`GEOIP,cn,DIRECT`，这样可以避免一些新的国内域名走代理问题 @ZZMISKING

**Comment by ieasyseek** [comment]
请问是在 极简配置文件https://raw.githubusercontent.com/GMOogway/shadowrocket-rules/master/docs/03.shadowsocks_tiny.conf
加入FINAL,PROXY 吗？
示例：
[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = system
ipv6 = false
prefer-ipv6 = false
dns-fallback-system = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
dns-direct-fallback-proxy = true

[Rule]
FINAL,PROXY  这样吗？
FINAL,DIRECT

[MITM]
enable = false

**Comment by GMOogway** [comment]
FINAL已经代表了最终，两个FINAL没有意义。最后是 FINAL,DIRECT，前面也没必要加 geoip,cn,direct了。你可以看一下小火箭配置说明。 @ieasyseek

**Comment by ieasyseek** [comment]
大佬 不是太明白
你说的 白名单时，在FINAL,PROXY前面，再加一句GEOIP,cn,DIRECT，这样可以避免一些新的国内域名 这个是在哪里添加？不是在配置文件？是在白名单模块？能说的详细些吗？GEOIP,cn,DIRECT 是加在 白名单模块规则里？

**Comment by Gorve-1** [comment]
为什么油管的广告都跳不了

**Comment by daniu118** [comment]
加载sr_direct_list.module ，后面跟一句 GEOIP,cn,DIRECT ，避免一些国内新域名走了代理。  请问大佬具体是在哪里添加，是配置文本里还是模块里面？

**Comment by GMOogway** [comment]
加在配置文件中。
  
  
  
  
  
  
  

  
  
>

**Comment by Jun3101** [comment]
如果是用黑名单，极简配置里，默认有了FINAL,DIRECT，是不是就不用修改了。
