### ISSUE TITLE
4.3更新后今日头条走了proxy导致打不开

### ISSUE THREAD

**Issue by douxy1994** [GMOogway/shadowrocket-rules#9]
4.3的规则里可能没有设置toutiao.com，开了小火箭今日头条提示网络错误，在direct里加了toutiao.com就正常了。

**Comment by GMOogway** [comment]
加一条 GEOIP,CN,DIRECT 即可解决类似问题

Dou Xiangyang ***@***.***>于2023年4月3日 周一11:36写道：

**Comment by douxy1994** [comment]
我是个小白。。这个要在哪里加呢？我只会每天早上用快捷指令进行更新。。

**Comment by GMOogway** [comment]
放在你配置文件 FINAL,PROXY 之前。

**Comment by douxy1994** [comment]
哦哦。我看懂了，也就是说direct和proxy这两个规则不需要全部打开啊。我下载的配置是final direct，我现在把proxy规则关掉，然后加上你说的这个再改成final proxy就好了对吧。

**Comment by GMOogway** [comment]
是的，理解没错，记得加一句 GEOIP,CN,DIRECT 。

**Comment by douxy1994** [comment]
我设置了之后就无法自动更新了，打开就是网络链接已中断。能不能帮我看看是不是设置有问题呢，谢谢。
![IMG_2214](https://user-images.githubusercontent.com/58248905/229956525-7d443eec-8dd2-467d-90bb-e614529f8f62.png)
这是我的设置。
![IMG_2216](https://user-images.githubusercontent.com/58248905/229956727-4857c613-e3ea-4391-8525-2079b3112095.png)
![IMG_2215](https://user-images.githubusercontent.com/58248905/229956732-eae31e19-d8b9-4a46-be8e-16d67f15433f.png)

**Comment by douxy1994** [comment]
> 看起来没有错误。 Dou Xiangyang ***@***.***>于2023年4月5日 周三09:18写道：
> […](#)

好奇怪，这样设置后自动更新就不行了。手动运行快捷指令，跳转过来也是网络连接已断开

**Comment by douxy1994** [comment]
> 看起来没有错误。 Dou Xiangyang ***@***.***>于2023年4月5日 周三09:18写道：
> […](#)

我发现如果我在模块中把direct，proxy和reject三个规则都打开就能更新，关掉proxy就不行了。但是如果三个都打开，那是不是白名单就没用了？

**Comment by GMOogway** [comment]
你最后是final,proxy，加不加载proxy效果是一样的。你测试一下，看更新网址匹配到哪条规则了。

**Comment by douxy1994** [comment]
> 你最后是final,proxy，加不加载proxy效果是一样的。你测试一下，看更新网址匹配到哪条规则了。

我只保留了这两个网址，但运行跳转过去就是已断开，不行我就手动更新吧。
![IMG_2233](https://user-images.githubusercontent.com/58248905/230245788-155f8f17-a9b0-40fa-a9c8-eec747ea9129.png)

**Comment by douxy1994** [comment]
> 你最后是final,proxy，加不加载proxy效果是一样的。你测试一下，看更新网址匹配到哪条规则了。

我找到了原因。
在快捷指令中，我把更新规则的链接设置成了raw.githubusercontent那个，也就是要走代理的那个链接，因为jsdelivr会晚一天。
但是因为我走的白名单，并且没有加载proxy，这就导致raw.github这个链接会被认为走direct，因此无法运行提示网络连接已断开。
为了测试我把快捷指令的地址换成jsdelivr或者走白名单的同时加载proxy规则，都不会出现这个问题，但我又不想晚一天更新，所以我就还是加上GEOIP，CN，DIRECT后走白名单，但是同时把proxy规则也打开，这样应该就没有影响吧？

**Comment by GMOogway** [comment]
这个域名不会在direct列表中的。你的测试及理解没问题，但有一点，你得注意，你的dns解析或许存在污染。

**Comment by douxy1994** [comment]
> 这个域名不会在direct列表中的。你的测试及理解没问题，但有一点，你得注意，你的dns解析或许存在污染。

啊，麻烦看一下我这两张截图，一个是我刚刚直接打开的GitHub中的direct列表，一个是我最新的小火箭direct list，都可以看到githubusercontent.com，这是否意味着我的dns有问题？
![IMG_2267](https://user-images.githubusercontent.com/58248905/230607152-3c8fceaf-92fa-4eb2-89f4-684038a6f6c3.jpeg)
![IMG_2269](https://user-images.githubusercontent.com/58248905/230607186-726c3d87-4c1b-4e5d-931b-f04f042a60c2.jpeg)

**Comment by GMOogway** [comment]
content和contents不同啊。

Alvis ***@***.***>于2023年4月7日 周五20:16写道：

**Comment by douxy1994** [comment]
> content和contents不同啊。 Alvis ***@***.***>于2023年4月7日 周五20:16写道：
> […](#)

原来如此，尬住。谢谢。。
